spring:
  application:
    name: DS Project


  datasource:
    url: jdbc:postgresql://postgres.pios.autos:6432/postgres
    username: postgres
    password: huagank123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  routee:
    app-id:
    app-secret:
    sender: