spring:
  application:
    name: DS Project


  datasource:
    url: jdbc:postgresql://postgres.pios.autos:6432/postgres
    username: postgres
    password: huagank123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

debug: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    gr.hua.dit.project: DEBUG

#Custom application properties.
app:
  jwt:
    issuer: "street-food-go-api"
    audience: "external-systems"
    secret: "${JWT_SECRET:Er4d/6nmWX6RWjDQW6CpeQZZwi9+WoBrhdQ4XEKWY9o=}" #openssl rand -base64 32
    ttl-minutes: 60
  external-service:
    url: "http://localhost:8081" # Default for running locally without Docker
    api-key: "streetfoodgo-api-key"

server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true