spring:
  application:
    name: DS Project


  datasource:
    url: jdbc:postgresql://postgres.pios.autos:6432/postgres
    username: postgres
    password: huagank123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

debug: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    gr.hua.dit.project: DEBUG

routee:
  app-id: 5bba56ece4b0a43fbf239aae
  app-secret: kDsvtwHe3w
  sender: SFGo # δεν μπορω να γραψω ολοκληρο το StreetFoodGo :(

nominatim:
  url: "https://nominatim.openstreetmap.org/search"
  user-agent: "StreetFoodGo-Project/1.0 (it2022088@hua.gr)"